_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
action_size:
    value: 6
alpha:
    value: 0.0001
batch_size:
    value: 256
buffer_size:
    value: 10000
decay_rate:
    value: 0.9995
eps_end:
    value: 0.1
eps_start:
    value: 1
gamma:
    value: 0.99
n_episode:
    value: 10000
state_size:
    value: 16
tau:
    value: 0.1
update_step:
    value: 100
use_wandb:
    value: true
wandb_project:
    value: drl_assignment1
wandb_run_name:
    value: dqn
